feat: add MeetUp #2 details
OurTechCommunity/meetup pull request #1
Opened 2022-09-11 21:17 UTC by tusharnankani

2022-09-22 19:32 UTC, SirusCodes requested changes

2022-09-22 19:32 UTC, SirusCodes commented on 2.html
> +				>!
Can we add CFP here as well?

2022-10-02 15:53 UTC, tusharnankani commented on 2.html
> +				>!
https://forms.gle/n2UUxv7aHyumUTeFA

2022-10-02 16:00 UTC, tusharnankani commented on 2.html
> +				>!
Done.

2022-10-02 16:12 UTC, merged